# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Fabric Properties
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.16.10

# Mod Properties
mod_version=1.0.0
maven_group=net.nova.mysticshrubs
mod_id=mystic_shrubs

# Dependencies
fabric_version=0.116.1+1.21.4
modmenu_version=13.0.1